import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../../styles/main.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import Navbar from "@/components/Navbar";
import { CookiesProvider } from 'next-client-cookies/server';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body id="body" className={inter.className}>
          <CookiesProvider>
            <Navbar/>
          </CookiesProvider>
        {children}
      </body>
    </html>
  );
}
