import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../../styles/main.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import "../../../styles/admin.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="content-wrapper">
          <section className="table-section">{children}</section>
        </div>
      </body>
    </html>
  );
}
